GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhMzUzMDYzN2NlYWQ3NGY1NjdkNDA0MSIsImlhdCI6MTc4MjExMTcwNn0.uL4GvSZrdWcMCfmDQfJemyM3ZcErkwBKQ7ZpEy4xOq4