POST http://localhost:3001/api/focusSession
Content-Type: application/json

{
  "startTime": "2026-05-01T10:30:00Z",
  "duration": 40,
  "source": {
    "type": "task",
    "refId": "69f34f223547eb4cf32ab856",
    "onModel": "Task"
  }
}