PUT http://localhost:3001/api/notes/69f304897014d01160dd734a
Content-Type: application/json

{
  "title": "test",
  "content": "that was test",
  "source": {
    "type": "task",
    "refid": "fuck",
    
  }
}